# Generated by Django 2.2.4 on 2019-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='123.png', upload_to='post_pic'),
        ),
    ]
